config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"


resources :organizations do 
  resources :businesses
  resources :contacts
  resources :deals
end


resources :users
resources :sessions
resources :activities
post "/login", to: "sessions#create"
get "/logout", to: "sessions#destroy"

end

app/controllers/businesses_controller.rb
  class BusinessesController < ApplicationController

    before_action :require_login

  def index
    @businessses = Current.user.organization.businesses
  end

  def new
    @business = Business.new
    @organization = Current.user.organization
  end

  def show
    @business = Business.find(params[:id])
  end

  def create
    @business = Business.new(business_params)
    @business.organization = Current.user.organization
    if @business.save
      flash[:success] = "Saved business."
      redirect_to organization_business_path(@business.organization, @business)
    else
      flash[:danger] = "Error. Business was not saved."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @business = Business.find(params[:id])
    @organization = @business.organization
  end

  def update
    @business = Business.find(params[:id])

    if @business.update(business_params)
      redirect_to organization_business_path(@business.organization, @business)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def business_params
    params.require(:business).permit(:name)
  end
end

app/views/businesses/_form.html.haml
= bootstrap_form_for [organization, business] do |form|
  %div
    = form.text_field :name
    = form.submit 'Save Business'

app/views/businesses/edit.html.haml
%h1 Editing...
= render 'form', business: @business, organization: @organization

app/views/businesses/index.html.haml
%h1 Businesses
= link_to new_organization_business_path(Current.user.organization) do
  %button.btn.btn-primary.btn-sm{:type => "button"} New business
%ul.list-group
  - @businessses.each do |business|
    %li.list-group-item
      = link_to organization_business_path(Current.user.organization, business) do
        = business.name

app/views/businesses/new.html.haml
%h1 New Business
= render 'form', business: @business, organization: @organization

app/views/businesses/show.html.haml
= link_to 'Back to businessses', organization_businesses_path(@business.organization)
%h1
  = @business.name
  = link_to 'Edit', edit_organization_business_path(@business.organization, @business)
%strong.border-bottom Name
%p= @business.name
%p
  = render "activities/mini_form", active: @business
%h2
  Activities#{@business.activities.count}
- @business.activities.each do |activity|
  = activity.title