config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"


resources :organizations do 
  resources :businesses
  resources :contacts
  resources :deals
end


resources :users
resources :sessions
resources :activities
post "/login", to: "sessions#create"
get "/logout", to: "sessions#destroy"

end

app/views/shared/_flashes.html.haml
.position-absolute.top-0.start-50.translate-middle-x.w-50>
\%&gt;
- flash.each do |type,  msg|
  .alert.alert-
  = type
  alert-dismissible fade show" role="alert"&gt;
  \#{msg}
  %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}

app/views/shared/_nav.html.haml
.col.bg-primary.vh-100
  %ul.nav.flex-column
    %li.nav-item
      = link_to "Log In", new_user_path, class: "nav-link text-white"
    %li.nav-item
      = link_to "Deals", organization_deals_path(Current.user.organization), class: "nav-link text-white"
    %li.nav-item
      = link_to "Organizations", organizations_path, class: "nav-link text-white"
    %li.nav-item
      = link_to "Businesses", organization_businesses_path(Current.user.organization), class: "nav-link text-white"
    %li.nav-item
      = link_to "Contacts", organization_contacts_path(Current.user.organization), class: "nav-link text-white"
    %li.nav-item
      = link_to "Activities", activities_path, class: "nav-link text-white"
    %li.nav-item
      = link_to "Log out", "/logout", class: "nav-link text-white"
    %div
      %p= Current.user.email
      %p= Current.user.organization.name