config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"


resources :organizations do 
  resources :businesses
  resources :contacts
  resources :deals
end


resources :users
resources :sessions
resources :activities
post "/login", to: "sessions#create"
get "/logout", to: "sessions#destroy"

end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :users
  has_many :businesses
  has_many :deals
  has_many :contacts
  has_many :activities, as: :active


  ACTIVITY_TYPE_OPTIONS = [
      ["Follow Up"],
      ["Email"],
      ["Call"],
      ["Initial Touch"],
      ["Nurture Touch"]
  ]

  ACTIVITY_STATUS_OPTIONS = [
    ["Todo"],
    ["In Progress"],
    ["Pause"],
    ["Complete"],
    ["Cancel"]
]


# TODO: fix
  def all_activities_for(child)
    output_array = []
    return child.each do |c|
      puts "==================================c"
      puts c.activities
      output_array << c.activities
    end
    puts "============ output array"
    p output_array
    output_array


  end




end

app/controllers/organizations_controller.rb
      class OrganizationsController < ApplicationController
    
      before_action :require_login

      def index
        @organizations = Organization.all
      end
    
      def new
        @organization = Organization.new
      end
    
      def show
        @organization = Organization.find(params[:id])
      end
    
      def create
        puts organization_params
        @organization = Organization.new(organization_params)
        if @organization.save
          redirect_to @organization
        else
          render :new, status: :unprocessable_entity
        end
      end
    
      def edit
        @organization = Organization.find(params[:id])
      end
    
      def update
        @organization = Organization.find(params[:id])
    
        if @organization.update(organization_params)
          redirect_to @organization
        else
          render :edit, status: :unprocessable_entity
        end
      end
    
      private
    
      def organization_params
        params.require(:organization).permit(:name)
      end
    end

app/views/organizations/_form.html.haml
= bootstrap_form_for organization do |form|
  %div
    = form.text_field :name
    = form.submit 'Save Organization'

app/views/organizations/edit.html.haml
%h1 Editing...
= render 'form', organization: @organization

app/views/organizations/index.html.haml
%h1 Organizations
= link_to new_organization_path do
  %button.btn.btn-primary.btn-sm{:type => "button"} New Organization
%ul.list-group
  - @organizations.each do |organization|
    %li.list-group-item
      = link_to organization_path(organization) do
        = organization.name

app/views/organizations/new.html.haml
%h1 New Organization
= render 'form', organization: @organization

app/views/organizations/show.html.haml
= link_to 'Back to organizations', organization_path
= bootstrap_form_for @organization do |form|
  %h1
    = @organization.name
    = link_to 'Edit', edit_organization_path(@organization)
  %strong.border-bottom Name
  %p= @organization.name
  %p
= render "activities/mini_form", active: @organization
%h2
  Activities#{@organization.activities.count}
- @organization.activities.each do |activity|
  = activity.title