config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"


resources :organizations do 
  resources :businesses
  resources :contacts
  resources :deals
end


resources :users
resources :sessions
resources :activities
post "/login", to: "sessions#create"
get "/logout", to: "sessions#destroy"

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :active, polymorphic: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_action :require_login

  def index
    @activities = Activity.all
  end

  def new
    @activity = Activity.new
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def create
    puts "============================== params"
    p activity_params
    @activity = Activity.new(activity_params)


    #Set user as the activity type if no other active item is given
    if @activity.active_type.nil?
      @activity.active_id = Current.user.id
      @activity.active_type = "User"
    end

    puts "================== p activity"
    puts p @activity


    if @activity.save
      redirect_to @activity
    else
      flash[:danger] = "Activity was not created."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])

    if @activity.update(activity_params)
      redirect_to @activity
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:title, :activity_type, :status, :active_type, :active_id, :due_date)
  end

end

app/views/activities/_form.html.haml
= bootstrap_form_for activity do |form|
  %div
    = form.text_field :title
    = form.submit 'Save Activity'

app/views/activities/_mini_form.html.haml
/ Button trigger modal
%button.btn.btn-primary{"data-bs-target" => "#newActivity", "data-bs-toggle" => "modal", :type => "button"}
  New Activity
/ Modal
#newActivity.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "newActivityLabel", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %h1#newActivityLabel.modal-title.fs-5 New Activity
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
      .modal-body
        = bootstrap_form_for @activity || Activity.new do |form|
          %div
            = form.text_field :title
            = form.select :activity_type, Organization::ACTIVITY_TYPE_OPTIONS, { class: "border border-secondary"}
            = form.select :status, Organization::ACTIVITY_STATUS_OPTIONS, { class: "border border-secondary"}
            = form.hidden_field :active_type, value: active.class.name
            = form.hidden_field :active_id, value: active.id
            = form.date_field :due_date
      .modal-footer
        %button.btn.btn-secondary{"data-bs-dismiss" => "modal", :type => "button"} Close
        %div{"data-bs-dismiss" => "modal"}
          = form.submit 'Save Activity', class: "btn btn-primary"

app/views/activities/edit.html.haml
%h1 Editing...
= render 'form', activity: @activity

app/views/activities/index.html.haml
%h1 Activities
= link_to new_activity_path do
  %button.btn.btn-primary.btn-sm{:type => "button"} New activity
%h2
  = Current.user.email
  's Activities
%ul.list-group
  - Current.user.activities.each do |activity|
    %li.list-group-item
      = link_to activity do
        = activity.title
%h2
  = Current.user.organization.name
  's Activities
%ul.list-group

app/views/activities/new.html.haml
%h1 New Activity
= render 'form', activity: @activity

app/views/activities/show.html.haml
= link_to 'Back to activities', activities_path
%h1
  = @activity.title
  = link_to 'Edit', edit_activity_path(@activity)
%strong.border-bottom Ntitleame
%p= @activity.title
%p